spring:
    application:
        name: host-tracker
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/hosttracker
        password: hosttracker
        username: hosttracker
    flyway:
        baselineOnMigrate: true
        enabled: true
        locations: classpath:db/migration
        schemas: public
