CREATE TABLE IF NOT EXISTS url
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value      VARCHAR(200)                             NOT NULL,
    period     FLOAT                                    NOT NULL,
    status     VARCHAR(200),
    ping_time     INTEGER,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_url PRIMARY KEY (id)
);

-- id url_value period status pingTime updated_at